name: Cache Warming

on:
  schedule:
    # Run daily at 2 AM UTC to warm caches
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  warm-caches:
    runs-on: ubuntu-latest
    environment: coenttb-com-server
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GH_USER }}"
          git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
      
      # Set up Docker Buildx for caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Restore existing caches
      - name: Cache Swift dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/swift
            .build
          key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      # Warm Swift Package Manager cache
      - name: Warm Swift dependencies cache
        run: |
          echo "🔥 Warming Swift Package Manager cache..."
          if [ -f Package.swift ]; then
            swift package resolve
            echo "✅ Swift dependencies resolved"
          fi
      
      # Warm Docker cache by building the image
      - name: Warm Docker build cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: cache-warmed:latest
          build-args: |
            GH_PAT=${{ secrets.GH_PAT }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      
      # Move cache to avoid cache bloat
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      
      - name: Cache warming complete
        run: |
          echo "🎉 Cache warming completed successfully!"
          echo "Main workflows will now have warm caches to work with."